env:
    global:
        - PACKAGE="UnitTesting-example" # Package name
        - SUBLIME_TEXT_VERSION="3"

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python
          python: 3.3
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap

script:
    # testing syntax_test files
    - sh travis.sh run_syntax_tests

notifications:
    email: false
